/*
 * NASA Docket No. GSC-18,587-1 and identified as “The Bundle Protocol Core Flight
 * System Application (BP) v6.5”
 *
 * Copyright © 2020 United States Government as represented by the Administrator of
 * the National Aeronautics and Space Administration. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/*
 * Include
 */
#include "bplib_cbor_test_utils.h"
#include "bplib_crc.h"


/*
Primary Block: 
         CRC Type: 1
         Flags: 4
         Dest EID (scheme.node.service): 2.200.1
         Source EID (scheme.node.service): 2.100.1
         Report-To EID (scheme.node.service): 2.100.1
         Timestamp (created, seq): 755533838904, 0
         Lifetime: 3600000
         CRC Value: 0xB19
Canonical Block [0]: 
         Block Type: 6 (prev node block)
         Block Number: 6
         Flags: 0
         CRC Type: 1
         Offset Into Encoded Bundle: 42
Canonical Block [1]: 
         Block Type: 7 (age block)
         Block Number: 2
         Flags: 5
         CRC Type: 1
         Offset Into Encoded Bundle: 58
Canonical Block [2]: 
         Block Type: 10 (hop count)
         Block Number: 3
         Flags: 1
         CRC Type: 1
         Offset Into Encoded Bundle: 72
Canonical Block [3]: 
         Block Type: 15 (CREB or CTEB ?)
         Block Number: 4
         Flags: 2
         CRC Type: 1
         Offset Into Encoded Bundle: 84
Canonical Block [4]: 
         Block Type: 16 (CREB or CTEB ?)
         Block Number: 5
         Flags: 0
         CRC Type: 1
         Offset Into Encoded Bundle: 103
*/

unsigned char bundle_with_too_many_canonical_blocks[] = {
    0x9f, 0x89, 0x07, 0x04, 0x01, 0x82, 0x02, 0x82, 0x18, 0xc8, 0x01, 0x82,
    0x02, 0x82, 0x18, 0x64, 0x01, 0x82, 0x02, 0x82, 0x18, 0x64, 0x01, 0x82,
    0x1b, 0x00, 0x00, 0x00, 0xaf, 0xe9, 0x53, 0x7a, 0x38, 0x00, 0x1a, 0x00,
    0x36, 0xee, 0x80, 0x42, 0x0b, 0x19, 0x86, 0x06, 0x06, 0x00, 0x01, 0x47,
    0x82, 0x02, 0x82, 0x19, 0x01, 0x2c, 0x02, 0x42, 0x25, 0xd4, 0x86, 0x07,
    0x02, 0x05, 0x01, 0x45, 0x1a, 0x00, 0x01, 0xa5, 0xe0, 0x42, 0x3a, 0xed,
    0x86, 0x0a, 0x03, 0x01, 0x01, 0x43, 0x82, 0x0f, 0x03, 0x42, 0xf8, 0x13,
    0x86, 0x0f, 0x04, 0x02, 0x01, 0x4a, 0x83, 0x0a, 0x02, 0x82, 0x02, 0x82,
    0x19, 0x01, 0x2f, 0x01, 0x42, 0x25, 0xc7, 0x86, 0x10, 0x05, 0x00, 0x01,
    0x52, 0x85, 0x01, 0x04, 0x00, 0x82, 0x02, 0x82, 0x19, 0x01, 0x2f, 0x01,
    0x82, 0x02, 0x82, 0x19, 0x01, 0x31, 0x02, 0x42, 0x66, 0xce, 0x86, 0x01,
    0x01, 0x00, 0x01, 0x54, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0c,
    0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x0a,
    0x42, 0x7a, 0x2f, 0xff
    };

/*
** generated by printing the bundle in
** tools/openc3-cosmos-dtnfsw/targets/DTNFSW/procedures/bpnode_contact_loopback_test.py
** warning: this binary seems to have errors, due to the way I printed / copied it
*/
unsigned char bad_bundle[] = {
    0x9f, 0x89, 0x07, 0x04, 0x01, 0x82, 0x02, 0x82, 0x18, 0xc8, 0x01, 0x82,
    0x02, 0x82, 0x18, 0x01, 0x82, 0x02, 0x82, 0x18, 0x01, 0x82, 0x1b, 0x00,
    0x00, 0x00, 0xaf, 0xe9, 0x00, 0x1a, 0x00, 0xee, 0x80, 0x0b, 0x19, 0x86,
    0x01, 0x01, 0x00, 0x01, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa,
    0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa,
    0xc6, 0x8f, 0xff
};

/*
Primary Block: 
         CRC Type: 1
         Flags: 4
         Dest EID (scheme.node.service): 2.200.1
         Source EID (scheme.node.service): 2.100.1
         Report-To EID (scheme.node.service): 2.100.1
         Timestamp (created, seq): 755533838904, 0
         Lifetime: 3600000
         CRC Value: 0xB19
Canonical Block [0]: 
         Block Type: 1
         Block Number: 1
         Flags: 0
         CRC Type: 1
         Offset Into Encoded Bundle: 42
*/
unsigned char primary_and_payload_with_aa_x_20[] = {
    0x9f, 0x89, 0x07, 0x04, 0x01, 0x82, 0x02, 0x82, 
    0x18, 0xc8, 0x01, 0x82, 0x02, 0x82, 0x18, 0x64, 
    0x01, 0x82, 0x02, 0x82, 0x18, 0x64, 0x01, 0x82, 
    0x1b, 0x00, 0x00, 0x00, 0xaf, 0xe9, 0x53, 0x7a, 
    0x38, 0x00, 0x1a, 0x00, 0x36, 0xee, 0x80, 0x42, 
    0x0b, 0x19, 0x86, 0x01, 0x01, 0x00, 0x01, 0x54, 
    0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 
    0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 
    0xaa, 0xaa, 0xaa, 0xaa, 0x42, 0xc6, 0x8f, 0xff,
};


void Test_BPLib_CBOR_DecodeBundle_NullInputErrors(void)
{
    BPLib_Bundle_t bundle;

    /* both null */
    UtAssert_INT32_EQ(BPLib_CBOR_DecodeBundle(NULL, 0, NULL), BPLIB_NULL_PTR_ERROR);
    
    /* CandBundle valid and bundle null */
    UtAssert_INT32_EQ(BPLib_CBOR_DecodeBundle(primary_and_payload_with_aa_x_20, 0, NULL), BPLIB_NULL_PTR_ERROR);
    
    /* CandBundle null and bundle valid */
    UtAssert_INT32_EQ(BPLib_CBOR_DecodeBundle(NULL, 0, &bundle), BPLIB_NULL_PTR_ERROR);
}


void Test_BPLib_CBOR_DecodeBundle_LengthError(void)
{
    BPLib_Bundle_t bundle;

    /* CandBundleLen expected to be at least 2 */
    UtAssert_INT32_EQ(BPLib_CBOR_DecodeBundle(primary_and_payload_with_aa_x_20, 2, &bundle),
        BPLIB_CBOR_DEC_BUNDLE_TOO_SHORT_ERR);
}

void Test_BPLib_CBOR_DecodeBundle_DecodeError(void)
{
    BPLib_Bundle_t bundle;
    BPLib_Status_t ReturnStatus;
    memset(&bundle, 0, sizeof(bundle));
    bundle.blob = NULL;

    ReturnStatus = BPLib_CBOR_DecodeBundle(bad_bundle,
                                           sizeof(bad_bundle),
                                           &bundle);

    UtAssert_INT32_EQ(ReturnStatus, BPLIB_CBOR_DEC_PRIM_SRC_EID_DEC_ERR);

}



void Test_BPLib_CBOR_DecodeBundle_PrimaryAndPayload(void)
{
    BPLib_Bundle_t bundle;
    BPLib_Status_t ReturnStatus;
    memset(&bundle, 0, sizeof(bundle));
    bundle.blob = NULL;

    ReturnStatus = BPLib_CBOR_DecodeBundle(primary_and_payload_with_aa_x_20,
                                           sizeof(primary_and_payload_with_aa_x_20),
                                           &bundle);

    UtAssert_INT32_EQ(ReturnStatus, BPLIB_SUCCESS);

    /*
    ** Verify Primary Block metadata
    */
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.CrcType, (uint64_t) BPLib_CRC_Type_CRC16);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.BundleProcFlags, 4);

    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.DestEID.Scheme, 2);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.DestEID.Node, 200);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.DestEID.Service, 1);

    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.SrcEID.Scheme, 2);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.SrcEID.Node, 100);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.SrcEID.Service, 1);

    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.ReportToEID.Scheme, 2);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.ReportToEID.Node, 100);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.ReportToEID.Service, 1);

    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.Timestamp.CreateTime, 755533838904);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.Timestamp.SequenceNumber, 0);
    
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.Lifetime, 3600000);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.CrcVal, 0x0b19);

    /*
    ** Verify Payload metadata
    */
    UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.BlockType, (uint64_t) BPLib_BlockType_Payload);
    UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.BlockNum, 1);
    UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.BundleProcFlags, 0);
    UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.CrcType, (uint64_t) BPLib_CRC_Type_CRC16);
}



void Test_BPLib_CBOR_DecodeBundle_MaxCanonicalBlockError(void)
{
    BPLib_Bundle_t bundle;
    BPLib_Status_t ReturnStatus;
    memset(&bundle, 0, sizeof(bundle));
    bundle.blob = NULL;

    ReturnStatus = BPLib_CBOR_DecodeBundle(bundle_with_too_many_canonical_blocks,
                                           sizeof(bundle_with_too_many_canonical_blocks),
                                           &bundle);

    UtAssert_INT32_EQ(ReturnStatus, BPLIB_CBOR_DEC_BUNDLE_MAX_BLOCKS_ERR);

}








void Test_BPLib_CBOR_DecodeBundle_CrcNone(void)
{
    BPLib_Bundle_t bundle;
    BPLib_Status_t ReturnStatus;
    memset(&bundle, 0, sizeof(bundle));

    /*
    Primary Block: 
            CRC Type: 0
            Flags: 4
            Dest EID (scheme.node.service): 2.200.1
            Source EID (scheme.node.service): 2.100.1
            Report-To EID (scheme.node.service): 2.100.1
            Timestamp (created, seq): 755533838904, 0
            Lifetime: 3600000
            CRC Value: 0x0
    Canonical Block [0]: 
            Block Type: 1
            Block Number: 1
            Flags: 0
            CRC Type: 0
            Header Offset: 40
            Data Offset: 47
            Payload Block Data Length: 30 bytes
            CRC Value: 0x0
    */
    unsigned char primary_and_payload_with_crc_none[] = {
        0x9f, 0x89, 0x07, 0x04, 0x00, 0x82, 0x02, 0x82, 
        0x18, 0xc8, 0x01, 0x82, 0x02, 0x82, 0x18, 0x64, 
        0x01, 0x82, 0x02, 0x82, 0x18, 0x64, 0x01, 0x82, 
        0x1b, 0x00, 0x00, 0x00, 0xaf, 0xe9, 0x53, 0x7a, 
        0x38, 0x00, 0x1a, 0x00, 0x36, 0xee, 0x80, 0x20, 
        0x86, 0x01, 0x01, 0x00, 0x00, 0x58, 0x1e, 0xaa, 
        0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 
        0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 
        0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 
        0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x20, 0xff,
    };

    ReturnStatus = BPLib_CBOR_DecodeBundle(primary_and_payload_with_crc_none,
                                           sizeof(primary_and_payload_with_crc_none),
                                           &bundle);

    UtAssert_INT32_EQ(ReturnStatus, BPLIB_SUCCESS);

    /*
    ** Verify Primary Block metadata
    */
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.CrcType, (uint64_t) BPLib_CRC_Type_None);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.BundleProcFlags, 4);

    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.DestEID.Scheme, 2);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.DestEID.Node, 200);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.DestEID.Service, 1);

    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.SrcEID.Scheme, 2);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.SrcEID.Node, 100);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.SrcEID.Service, 1);

    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.ReportToEID.Scheme, 2);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.ReportToEID.Node, 100);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.ReportToEID.Service, 1);

    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.Timestamp.CreateTime, 755533838904);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.Timestamp.SequenceNumber, 0);
    
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.Lifetime, 3600000);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.FragmentOffset, 0);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.TotalAduLength, 30);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.CrcVal, 0);
    
    /*
    ** Verify Payload metadata
    */
   UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.BlockType, (uint64_t) BPLib_BlockType_Payload);
   UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.BlockNum, 1);
   UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.BundleProcFlags, 0);
   UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.CrcType, (uint64_t) BPLib_CRC_Type_None);
   UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.CrcVal, 0);
}









void Test_BPLib_CBOR_DecodeBundle_Crc32(void)
{
    BPLib_Bundle_t bundle;
    BPLib_Status_t ReturnStatus;
    memset(&bundle, 0, sizeof(bundle));

    /*
    Primary Block: 
             CRC Type: 2
             Flags: 4
             Dest EID (scheme.node.service): 2.200.1
             Source EID (scheme.node.service): 2.100.1
             Report-To EID (scheme.node.service): 2.100.1
             Timestamp (created, seq): 755533838904, 0
             Lifetime: 3600000
             CRC Value: 0x65315CD
    Canonical Block [0]: 
             Block Type: 1
             Block Number: 1
             Flags: 0
             CRC Type: 2
             Header Offset: 44
             Data Offset: 51
             Payload Block Data Length: 40 bytes
             CRC Value: 0x3C30C058
    */

    unsigned char primary_and_payload_with_crc_32[] = {
        0x9f, 0x89, 0x07, 0x04, 0x02, 0x82, 0x02, 0x82, 
        0x18, 0xc8, 0x01, 0x82, 0x02, 0x82, 0x18, 0x64, 
        0x01, 0x82, 0x02, 0x82, 0x18, 0x64, 0x01, 0x82, 
        0x1b, 0x00, 0x00, 0x00, 0xaf, 0xe9, 0x53, 0x7a, 
        0x38, 0x00, 0x1a, 0x00, 0x36, 0xee, 0x80, 0x44, 
        0x06, 0x53, 0x15, 0xcd, 0x86, 0x01, 0x01, 0x00, 
        0x02, 0x58, 0x28, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 
        0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 
        0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 
        0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 
        0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 
        0xaa, 0xaa, 0xaa, 0x44, 0x3c, 0x30, 0xc0, 0x58, 
        0xff,
    };

    ReturnStatus = BPLib_CBOR_DecodeBundle(primary_and_payload_with_crc_32,
                                           sizeof(primary_and_payload_with_crc_32),
                                           &bundle);

    UtAssert_INT32_EQ(ReturnStatus, BPLIB_SUCCESS);

    /*
    ** Verify Primary Block metadata
    */
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.CrcType, (uint64_t) BPLib_CRC_Type_CRC32C);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.BundleProcFlags, 4);

    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.DestEID.Scheme, 2);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.DestEID.Node, 200);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.DestEID.Service, 1);

    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.SrcEID.Scheme, 2);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.SrcEID.Node, 100);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.SrcEID.Service, 1);

    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.ReportToEID.Scheme, 2);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.ReportToEID.Node, 100);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.ReportToEID.Service, 1);

    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.Timestamp.CreateTime, 755533838904);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.Timestamp.SequenceNumber, 0);
    
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.Lifetime, 3600000);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.FragmentOffset, 0);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.TotalAduLength, 40);
    UtAssert_EQ(uint64_t, bundle.blocks.PrimaryBlock.CrcVal, 0x065315CD);
    
    /*
    ** Verify Payload metadata
    */
   UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.BlockType, (uint64_t) BPLib_BlockType_Payload);
   UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.BlockNum, 1);
   UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.BundleProcFlags, 0);
   UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.CrcType, (uint64_t) BPLib_CRC_Type_CRC32C);
   UtAssert_EQ(uint64_t, bundle.blocks.PayloadHeader.CrcVal, 0x3C30C058);
}




/*
** BPLib_CBOR_EncodePrimary Tests
*/

void Test_BPLib_CBOR_EncodePrimary_NullInputErrors(void)
{
    BPLib_Status_t ReturnStatus;
    BPLib_Bundle_t StoredBundleIn;
    char OutputBuffer[512];
    size_t OutputBufferSize = sizeof(OutputBuffer);
    size_t NumBytesCopied;

    /* all null */
    ReturnStatus = BPLib_CBOR_EncodePrimary(NULL, NULL, 0, NULL);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_NULL_PTR_ERROR);

    /* StoredBundleIn NULL */
    ReturnStatus = BPLib_CBOR_EncodePrimary(NULL, OutputBuffer, OutputBufferSize, &NumBytesCopied);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_NULL_PTR_ERROR);

    /* OutputBuffer NULL */
    ReturnStatus = BPLib_CBOR_EncodePrimary(&StoredBundleIn, NULL, 0, &NumBytesCopied);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_NULL_PTR_ERROR);

    /* NumBytesCopied NULL */
    ReturnStatus = BPLib_CBOR_EncodePrimary(&StoredBundleIn, OutputBuffer, OutputBufferSize, NULL);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_NULL_PTR_ERROR);
}


void Test_BPLib_CBOR_EncodePrimary_Nominal(void)
{
    BPLib_Status_t ReturnStatus;
    BPLib_Bundle_t StoredBundleIn;
    char OutputBuffer[512];
    size_t OutputBufferSize = sizeof(OutputBuffer);
    size_t NumBytesCopied;

    /* Setup nominal inputs */
    memset(&StoredBundleIn, 0, sizeof(StoredBundleIn));

    /* Call UUT and check status */
    ReturnStatus = BPLib_CBOR_EncodePrimary(&StoredBundleIn, OutputBuffer, OutputBufferSize, &NumBytesCopied);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_SUCCESS);
}


/*
** BPLib_CBOR_EncodeExtensionBlock Tests
*/


void Test_BPLib_CBOR_EncodeExtensionBlock_NullInputErrors(void)
{
    BPLib_Status_t ReturnStatus;
    BPLib_Bundle_t StoredBundleIn;
    char OutputBuffer[512];
    size_t OutputBufferSize = sizeof(OutputBuffer);
    size_t NumBytesCopied;

    /* all null */
    ReturnStatus = BPLib_CBOR_EncodeExtensionBlock(NULL, 0, NULL, 0, NULL);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_NULL_PTR_ERROR);

    /* StoredBundleIn NULL */
    ReturnStatus = BPLib_CBOR_EncodeExtensionBlock(NULL, 0, OutputBuffer, OutputBufferSize, &NumBytesCopied);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_NULL_PTR_ERROR);

    /* OutputBuffer NULL */
    ReturnStatus = BPLib_CBOR_EncodeExtensionBlock(&StoredBundleIn, 0, NULL, 0, &NumBytesCopied);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_NULL_PTR_ERROR);

    /* NumBytesCopied NULL */
    ReturnStatus = BPLib_CBOR_EncodeExtensionBlock(&StoredBundleIn, 0, OutputBuffer, OutputBufferSize, NULL);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_NULL_PTR_ERROR);
}

void Test_BPLib_CBOR_EncodeExtensionBlock_Nominal(void)
{
    BPLib_Status_t ReturnStatus;
    BPLib_Bundle_t StoredBundleIn;
    char OutputBuffer[512];
    size_t OutputBufferSize = sizeof(OutputBuffer);
    size_t NumBytesCopied;

    /* Setup nominal inputs */
    memset(&StoredBundleIn, 0, sizeof(StoredBundleIn));

    /* Call UUT and check status */
    ReturnStatus = BPLib_CBOR_EncodeExtensionBlock(&StoredBundleIn, 0, OutputBuffer, OutputBufferSize, &NumBytesCopied);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_SUCCESS);
}


/*
** BPLib_CBOR_EncodePayload Tests
*/

void Test_BPLib_CBOR_EncodePayload_NullInputErrors(void)
{
    BPLib_Status_t ReturnStatus;
    BPLib_Bundle_t StoredBundleIn;
    char OutputBuffer[512];
    size_t OutputBufferSize = sizeof(OutputBuffer);
    size_t NumBytesCopied;

    /* all null */
    ReturnStatus = BPLib_CBOR_EncodePayload(NULL, NULL, 0, NULL);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_NULL_PTR_ERROR);

    /* StoredBundleIn NULL */
    ReturnStatus = BPLib_CBOR_EncodePayload(NULL, OutputBuffer, OutputBufferSize, &NumBytesCopied);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_NULL_PTR_ERROR);

    /* OutputBuffer NULL */
    ReturnStatus = BPLib_CBOR_EncodePayload(&StoredBundleIn, NULL, 0, &NumBytesCopied);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_NULL_PTR_ERROR);

    /* NumBytesCopied NULL */
    ReturnStatus = BPLib_CBOR_EncodePayload(&StoredBundleIn, OutputBuffer, OutputBufferSize, NULL);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_NULL_PTR_ERROR);
}


void Test_BPLib_CBOR_EncodePayload_Nominal(void)
{
    BPLib_Status_t ReturnStatus;
    BPLib_Bundle_t StoredBundleIn;
    char OutputBuffer[512];
    size_t OutputBufferSize = sizeof(OutputBuffer);
    size_t NumBytesCopied;

    /* Setup nominal inputs */
    memset(&StoredBundleIn, 0, sizeof(StoredBundleIn));

    /* Call UUT and check status */
    ReturnStatus = BPLib_CBOR_EncodePayload(&StoredBundleIn, OutputBuffer, OutputBufferSize, &NumBytesCopied);
    UtAssert_INT32_EQ(ReturnStatus, BPLIB_NULL_PTR_ERROR);
}




void TestBplibCbor_Register(void)
{
    UtTest_Add(Test_BPLib_CBOR_DecodeBundle_NullInputErrors, BPLib_CBOR_Test_Setup, BPLib_CBOR_Test_Teardown, "Test_BPLib_CBOR_DecodeBundle_NullInputErrors");
    UtTest_Add(Test_BPLib_CBOR_DecodeBundle_LengthError, BPLib_CBOR_Test_Setup, BPLib_CBOR_Test_Teardown, "Test_BPLib_CBOR_DecodeBundle_LengthError");
    UtTest_Add(Test_BPLib_CBOR_DecodeBundle_DecodeError, BPLib_CBOR_Test_Setup, BPLib_CBOR_Test_Teardown, "Test_BPLib_CBOR_DecodeBundle_DecodeError");
    UtTest_Add(Test_BPLib_CBOR_DecodeBundle_PrimaryAndPayload, BPLib_CBOR_Test_Setup, BPLib_CBOR_Test_Teardown, "Test_BPLib_CBOR_DecodeBundle_PrimaryAndPayload");
    UtTest_Add(Test_BPLib_CBOR_DecodeBundle_MaxCanonicalBlockError, BPLib_CBOR_Test_Setup, BPLib_CBOR_Test_Teardown, "Test_BPLib_CBOR_DecodeBundle_MaxCanonicalBlockError");
    UtTest_Add(Test_BPLib_CBOR_DecodeBundle_CrcNone, BPLib_CBOR_Test_Setup, BPLib_CBOR_Test_Teardown, "Test_BPLib_CBOR_DecodeBundle_CrcNone");
    UtTest_Add(Test_BPLib_CBOR_DecodeBundle_Crc32, BPLib_CBOR_Test_Setup, BPLib_CBOR_Test_Teardown, "Test_BPLib_CBOR_DecodeBundle_Crc32");

    UtTest_Add(Test_BPLib_CBOR_EncodePrimary_NullInputErrors, BPLib_CBOR_Test_Setup, BPLib_CBOR_Test_Teardown, "Test_BPLib_CBOR_EncodePrimary_NullInputErrors");
    UtTest_Add(Test_BPLib_CBOR_EncodePrimary_Nominal, BPLib_CBOR_Test_Setup, BPLib_CBOR_Test_Teardown, "Test_BPLib_CBOR_EncodePrimary_Nominal");

    UtTest_Add(Test_BPLib_CBOR_EncodeExtensionBlock_NullInputErrors, BPLib_CBOR_Test_Setup, BPLib_CBOR_Test_Teardown, "Test_BPLib_CBOR_EncodeExtensionBlock_NullInputErrors");
    UtTest_Add(Test_BPLib_CBOR_EncodeExtensionBlock_Nominal, BPLib_CBOR_Test_Setup, BPLib_CBOR_Test_Teardown, "Test_BPLib_CBOR_EncodeExtensionBlock_Nominal");

    UtTest_Add(Test_BPLib_CBOR_EncodePayload_NullInputErrors, BPLib_CBOR_Test_Setup, BPLib_CBOR_Test_Teardown, "Test_BPLib_CBOR_EncodePayload_NullInputErrors");
    UtTest_Add(Test_BPLib_CBOR_EncodePayload_Nominal, BPLib_CBOR_Test_Setup, BPLib_CBOR_Test_Teardown, "Test_BPLib_CBOR_EncodePayload_Nominal");
}
