#!/bin/bash
bplib-unit-test-functional-err() {
   echo "bplib-unit-test-functional exited on error."
   exit 1
}
trap bplib-unit-test-functional-err ERR

# bplib-unit-test-functional
# Based on bplib/.github/workflows/unit-test-functional.yml

   cd $CFS_HOME
   BPLIB_SOURCE=../repos/cfs-bundle/libs/bplib
   BPLIB_BUILD=TBD # Set later for Debug/Release and OSAL/POSIX

   if { [ "$1" = "Debug" ] || [ "$1" = "Release" ]; } &&
      { [ "$2" = "OSAL" ]  || [ "$2" = "POSIX" ]; }; then
      MATRIX_BUILD_TYPE="${1}"
      MATRIX_OS_LAYER="${2}"
      MATRIX_ID="matrix-${MATRIX_BUILD_TYPE}-${MATRIX_OS_LAYER}"
      echo "Running $0 $1 $2"
   else
      echo "$0 $1 $2"
      echo "Usage: $0 [Debug, Release] [OSAL, POSIX]"
      exit 1
   fi

   BPLIB_BUILD="bplib-build-${MATRIX_ID}"

   # setup-osal has already been run.
   # setup-cbor was already done by install-toolchain.
   # bplib-dep dependencies are satisfied.

   # Create the build folder based on Debug/Release and OSAL/POSIX
   cmake \
          -DCMAKE_BUILD_TYPE="${MATRIX_BUILD_TYPE}" \
          -DBPLIB_OS_LAYER="${MATRIX_OS_LAYER}" \
          -DCMAKE_PREFIX_PATH=/usr/local/lib/cmake \
          -S "${BPLIB_SOURCE}" -B "${BPLIB_BUILD}"

   # Build bplib
   cd "${BPLIB_BUILD}"
   make all

   # Run tests, if available.
   if [ -e '${MATRIX_ID}/CTestTestfile.cmake' ]; then RUN_TESTS=True; fi;
   if ["${RUN_TESTS}" = "True" ]; then
      ctest --output-on-failure 2>&1 | tee test.log
   fi
