#!/bin/bash
build-bplib-err() {
   echo "build-bplib exited on error."
   exit 1
}
trap build-bplib-err ERR
set -o pipefail

# Log filename with DOY-HHMM
LOG_FILENAME=bplib-test-driver-$(date +%y%j-%H%M)

# Log filename with YYYYmmdd-HHMM
# LOG_FILENAME=bplib-test-driver-$(date +%Y%m%d-%H%M).log

echo "Logging to ${CFS_HOME}/${LOG_FILENAME}*.log"

   cd $CFS_HOME
   ./bplib-unit-test-functional Debug OSAL |& tee "${LOG_FILENAME}-d-o.log"
   ./bplib-unit-test-functional Release OSAL |& tee -a "${LOG_FILENAME}-r-o.log"
   ./bplib-unit-test-functional Debug POSIX |& tee -a "${LOG_FILENAME}-d-p.log"
   ./bplib-unit-test-functional Release POSIX |& tee -a "${LOG_FILENAME}-r-p.log"

   # Errors are trapped, causing the script to exit.
   # If the script gets here, there were no errors.
   echo "${0} finished with no errors"

