#!/bin/bash
bplib-clean-err() {
   echo "bplib-clean exited on error."
   exit 1
}
trap bplib-clean-err ERR

   cd $BPLIB_HOME

   BPLIB_DELETE_LIST=( \
      "bplib-build-matrix-Debug-OSAL" \
      "bplib-build-matrix-Release-OSAL" \
      "bplib-build-matrix-Debug-POSIX" \
      "bplib-build-matrix-Release-POSIX" \
   )

   echo "In $(pwd)"
   echo "Ready to delete:"
   echo ${BPLIB_DELETE_LIST[@]}
   read -p "Delete [y|N]?" choice
   case "${choice}" in
      y|Y ) \
         (set -x; rm -rf ${BPLIB_DELETE_LIST[@]});;
      * ) \
         echo "bplib-clean canceled."
    esac

