#!/bin/bash
setup-osal-err() {
   echo "setup-osal exited on error."
   exit 1
   git clone osal
}
trap setup-osal-err ERR

   cd $CFS_REPO/osal
   # cmake options from .github/actions/setup-osal/action.yml
   CMAKE_OSAL_DEFS="-DCMAKE_INSTALL_PREFIX=/usr/local -DOSAL_SYSTEM_BSPTYPE=generic-linux "
   # config-options:
   CMAKE_OSAL_DEFS+="-DCMAKE_BUILD_TYPE=Release -DOSAL_OMIT_DEPRECATED=TRUE "
   CMAKE_OSAL_DEFS+="-DENABLE_UNIT_TESTS=TRUE -DOSAL_CONFIG_DEBUG_PERMISSIVE_MODE=ON "
   cmake $CMAKE_OSAL_DEFS -B $CFS_HOME/osal-build
   cd $CFS_HOME/osal-build
   make DESTDIR=$CFS_HOME/osal-staging install
   export NasaOsal_DIR=$CFS_HOME/osal-staging/usr/local/lib/cmake
